### ISSUE TITLE
Crash when muting/unmuting server

### ISSUE THREAD

**Issue by fearek** [JustOptimize/ShowHiddenChannels#214]
```
sentry.4aa65d81f09c738c28ce.js:14 TypeError: Cannot read properties of undefined (reading 'record')
    at en.forEachShownChannel (266f26a577fd777cd3c2.js:1:10190)
    at C (879c083c295e6dbe63ca.js:1:29044)
    at 879c083c295e6dbe63ca.js:1:28691
    at Object.os [as useMemo] (web.35a426710db29dd3edca.js:12:1327041)
    at t.useMemo (web.35a426710db29dd3edca.js:12:1440925)
    at A (879c083c295e6dbe63ca.js:1:28686)
    at 5f1a0b8ffd4bdfb26f99.js:1:169340
    at aY (web.35a426710db29dd3edca.js:12:1322668)
    at oM (web.35a426710db29dd3edca.js:12:1332723)
    at l (web.35a426710db29dd3edca.js:12:1381287)
    at lu (web.35a426710db29dd3edca.js:12:1370772)
    at ls (web.35a426710db29dd3edca.js:12:1370700)
    at lo (web.35a426710db29dd3edca.js:12:1370563)
    at s4 (web.35a426710db29dd3edca.js:12:1366933)
    at s3 (web.35a426710db29dd3edca.js:12:1365900)
    at v (web.35a426710db29dd3edca.js:12:1555532)
    at b (web.35a426710db29dd3edca.js:12:1556062)
    at T.C.<computed> (web.35a426710db29dd3edca.js:1:1271621)
    at L (web.35a426710db29dd3edca.js:1:1271386)
    at MessagePort.D (web.35a426710db29dd3edca.js:1:1271445)
S.t.<computed> @ web.35a426710db29dd3edca.js:12
(anonymous) @ sentry.4aa65d81f09c738c28ce.js:14
oA @ web.35a426710db29dd3edca.js:12
a.componentDidCatch.n.callback @ web.35a426710db29dd3edca.js:12
aa @ web.35a426710db29dd3edca.js:12
sg @ web.35a426710db29dd3edca.js:12
sT @ web.35a426710db29dd3edca.js:12
sI @ web.35a426710db29dd3edca.js:12
l_ @ web.35a426710db29dd3edca.js:12
ld @ web.35a426710db29dd3edca.js:12
s3 @ web.35a426710db29dd3edca.js:12
v @ web.35a426710db29dd3edca.js:12
b @ web.35a426710db29dd3edca.js:12
T.C.<computed> @ web.35a426710db29dd3edca.js:1
L @ web.35a426710db29dd3edca.js:1
D @ web.35a426710db29dd3edca.js:1
```

**Comment by JustOptimize** [comment]
Can you share your settings? I can't reproduce..

**Comment by fearek** [comment]
> Can you share your settings? I can't reproduce..

I didnt change settings after installing
it seems to happen on only one server
[Server that crashes](https://discord.com/invite/JKU6tey)

**Comment by JustOptimize** [comment]
Uh... still works :/ 
![image](https://github.com/user-attachments/assets/d69b16bc-1851-4a75-974f-ed25bb2fddd9)

**Comment by JustOptimize** [comment]
Are you running other plugins?

**Comment by fearek** [comment]
> Are you running other plugins?

yes, but even after disabling them and leaving only SHC, BDFDB, Zeres it still crashes
only when I disable SHC it doesnt crash

appears I was mistaken with default settings, the issue seems to be displaying hidden channels in seperate category.

**Comment by JustOptimize** [comment]
It crashes because categories have a channel limit so huge servers go over that limit, i'll look into it, thanks

**Comment by JustOptimize** [comment]
Can you confirm that [this](https://raw.githubusercontent.com/JustOptimize/ShowHiddenChannels/refs/heads/fix/crash-when-muting/ShowHiddenChannels.plugin.js) fixes the issue?

**Comment by fearek** [comment]
yup no crash anymore
