### ISSUE TITLE
Could Not Be Compiled error on startup

### ISSUE THREAD

**Issue by Orchidthederg** [JustOptimize/ShowHiddenChannels#216]
SHC Will not compile when starting BetterDiscord.
```
TypeError: Cannot destructure property 'rolePill' of 'WebpackModules.getByProps(...)' as it is undefined.
    at eval (betterdiscord://plugins/ShowHiddenChannels.plugin.js:153:13)
    at eval (betterdiscord://plugins/ShowHiddenChannels.plugin.js:1374:5)
    at eval (betterdiscord://plugins/ShowHiddenChannels.plugin.js:1375:3)
    at N.requireAddon (betterdiscord/renderer.js:5:28601)
    at N.loadAddon (betterdiscord/renderer.js:5:6221)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at N.loadAllAddons (betterdiscord/renderer.js:5:9278)
    at N.initialize (betterdiscord/renderer.js:5:3093)
    at N.initialize (betterdiscord/renderer.js:5:25382)
    at Object.startup (betterdiscord/renderer.js:5:408589)
```

(Current plugins: BDFDB, XenoLib, ZeresPluginLibrary, ImageUtilities, RoleMembers, ShowHiddenChannels)

**Comment by JustOptimize** [comment]
What version of ShowHiddenChannels are you using

**Comment by raphael-mottelet** [comment]
interesting, wich version are you using ? Could be a older one that got deprecated

**Comment by JustOptimize** [comment]
Closing as stale, probably he is just using an old version
