### ISSUE TITLE
Crashing on startup with latest Discord PTB

### ISSUE THREAD

**Issue by Mythra** [JustOptimize/ShowHiddenChannels#218]
Noticed the plugin failed to start loading today on PTB (I'm using the latest ShowHiddenChannels v0.5.4), the addon on discord shows a "Could not be compiled. See console for details", the logs on it are:

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at ./src/utils/modules.js (betterdiscord://plugins/ShowHiddenChannels.plugin.js:647:36)
    at __webpack_require__ (betterdiscord://plugins/ShowHiddenChannels.plugin.js:847:41)
    at ./src/components/UserMentionsComponent.jsx (betterdiscord://plugins/ShowHiddenChannels.plugin.js:429:6)
    at __webpack_require__ (betterdiscord://plugins/ShowHiddenChannels.plugin.js:847:41)
    at ./src/components/Lockscreen.jsx (betterdiscord://plugins/ShowHiddenChannels.plugin.js:299:80)
    at __webpack_require__ (betterdiscord://plugins/ShowHiddenChannels.plugin.js:847:41)
    at plugin (betterdiscord://plugins/ShowHiddenChannels.plugin.js:1035:36)
    at eval (betterdiscord://plugins/ShowHiddenChannels.plugin.js:1998:16)
    at eval (betterdiscord://plugins/ShowHiddenChannels.plugin.js:1999:7)
    at eval (betterdiscord://plugins/ShowHiddenChannels.plugin.js:2001:3)
    at eval (betterdiscord://plugins/ShowHiddenChannels.plugin.js:2004:12)
    at N.requireAddon (betterdiscord/renderer.js:5:28601)
    at N.loadAddon (betterdiscord/renderer.js:5:6221)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at N.loadAllAddons (betterdiscord/renderer.js:5:9278)
    at N.initialize (betterdiscord/renderer.js:5:3093)
    at N.initialize (betterdiscord/renderer.js:5:25382)
    at Object.startup (betterdiscord/renderer.js:5:408589)
```

Using PTB 341255 (b98134b), BetterDiscord Core v1.10.2, and ShowHiddenChannels v0.5.4 (the latest).

**Comment by JustOptimize** [comment]
Should be fixed with latest release (v0.5.5), can you confirm?

**Comment by 1Rolz** [comment]
its use-a-ble now. thx u.

**Comment by 1Rolz** [comment]
sorry for bad english. its perfect 100% use. no issue no error. 🙏

**Comment by JustOptimize** [comment]
> sorry for bad english. its perfect 100% use. no issue no error. 🙏

okeoke, thanks
