### ISSUE TITLE
Bug Compilations

### ISSUE THREAD

**Issue by vipgunner** [JustOptimize/ShowHiddenChannels#222]
I have this error : 
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at ./src/utils/modules.js (betterdiscord://plugins/ShowHiddenChannels.plugin.js:647:36)
    at __webpack_require__ (betterdiscord://plugins/ShowHiddenChannels.plugin.js:847:41)
    at ./src/components/UserMentionsComponent.jsx (betterdiscord://plugins/ShowHiddenChannels.plugin.js:429:6)
    at __webpack_require__ (betterdiscord://plugins/ShowHiddenChannels.plugin.js:847:41)
    at ./src/components/Lockscreen.jsx (betterdiscord://plugins/ShowHiddenChannels.plugin.js:299:80)
    at __webpack_require__ (betterdiscord://plugins/ShowHiddenChannels.plugin.js:847:41)
    at plugin (betterdiscord://plugins/ShowHiddenChannels.plugin.js:1035:36)
    at eval (betterdiscord://plugins/ShowHiddenChannels.plugin.js:1998:16)
    at eval (betterdiscord://plugins/ShowHiddenChannels.plugin.js:1999:7)
    at eval (betterdiscord://plugins/ShowHiddenChannels.plugin.js:2001:3)
    at eval (betterdiscord://plugins/ShowHiddenChannels.plugin.js:2004:12)
    at N.requireAddon (betterdiscord/renderer.js:5:28601)
    at N.loadAddon (betterdiscord/renderer.js:5:6221)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at N.loadAllAddons (betterdiscord/renderer.js:5:9278)
    at N.initialize (betterdiscord/renderer.js:5:3093)
    at N.initialize (betterdiscord/renderer.js:5:25382)
    at Object.startup (betterdiscord/renderer.js:5:408589)
can you help me ?

**Comment by sGxOxDs** [comment]
![image](https://github.com/user-attachments/assets/8af13c90-e3e5-4551-8071-b92727379fc6)
update to v0.5.5 is useful to me

**Comment by JustOptimize** [comment]
See #218
